server:
  servlet:
    port: 8080
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    url: 
    driver: org.mariadb.jdbc.Driver
    username: 
    password: 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate: 
      ddl-update: auto

logging:
  file:
    path: C:\log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    me.hong.kotlinspring: debug